name: ${project.name}
main: ${package}.${project.name}
version: ${project.version}
authors: [PotatoCraft Studio, Netherfoam, Timtower, KaiNoMood, Ghost_chu, Mgazul, TiaraRinne, sandtechnology]

description: Economy Shops plugin
#softdepend: [Herochat, Vault, Essentials, OpenInv] OLD Remove Herochat support.
#Now we only need Vault.
softdepend:
  - Vault
  - Reserve
  - PlaceholderAPI
  - NoCheatPlus
  - LuckPerms
  - PermissionEx
  - GroupManager
  - ClearLag
  - Essentials
  - CMI
  - PlotSquared
  - Residence
  - Towny
  - WorldGuard
  - Factions
  - ProtocolLib
  - LWC
  - BlockHub
  - Lands
  - GriefPrevention
  - JulySafe
  - FabledSkyblock

api-version: 1.13

commands:
  qs:
    description: QuickShop command
    usage: /qs
    aliases: [shop,qsshop,qshop,quickshop,chestshop,cshop]

permissions:
  quickshop.create.sell:
    description: Allows a player to sell from a shop
    default: op
  quickshop.create.buy:
    description: Allows a player to buy from a shop
    default: op
  quickshop.create.double:
    description: Allows a player to create a double shop
    default: op
  quickshop.create.changeprice:
    description: Allow a player to change their shop's price
    default: op
  quickshop.create.cmd:
    description: Allow a player to use /qs create to create a shop
    default: op
  quickshop.create.admin:
    description: Allow a player use /qs supercreate to create a shop bypass all protection checks
    default: op
  quickshop.create.changeitem:
    description: Allow a player to change their shop's item
    default: op
  quickshop.create.changeamount:
    description: Allow a player to change their shop's per bulk amount
    default: op
  quickshop.create.stacks:
    description: Allow a player to create a shop with stack items
    default: op
  quickshop.use:
    description: Allows a player to buy/sell using other players shops
    default: true
  quickshop.unlimited:
    description: Allows a Staff Member to use /qs unlimited and make a shop infinite
    default: op
  quickshop.bypass.<itemID>:
    description: Allows a player to sell <itemID>, even if its blacklisted
    default: op
  quickshop.other.destroy:
    description: Allows a Staff Member to destroy other players shops if they are locked in the config
    default: op
  quickshop.other.control:
    description: Allows a Staff Member to open control panel for other players shop
    default: op
  quickshop.other.open:
    description: Allows a Staff Member to open someone elses shop if they are locked in the config
    default: op
  quickshop.other.price:
    description: Allows a Staff Member to change the price of someone elses shop
    default: op
  quickshop.other.item:
    description: Allows a Staff Member to change the item of someone elses shop
    default: op
  quickshop.other.amount:
    description: Allows a Staff Member to change the per bulk amount of someone elses shop
    default: op
  quickshop.setowner:
    description: Allows a Staff Member to change the owner of any shop
    default: op
  quickshop.staff:
    description: Allow a shop owner to add staff to the shop
    default: op
  quickshop.find:
    description: Allows a player to locate the nearest shop that has a specific item type. Works in a 3 chunk radius.
    default: true
  quickshop.refill:
    description: Allows a Staff Member to refill the shop theyre looking at with the given number of items.
    default: op
  quickshop.empty:
    description: Allows a Staff Member to empty the shop theyre looking at of all items.
    default: op
  quickshop.debug:
    description: Switch to or from developer mode
    default: op
  quickshop.export:
    description: Allows exporting the database to a plain file
    default: op
  quickshop.alerts:
    description: Recive cheat alert, plugin warnings and update notify
    default: op
  quickshop.about:
    description: Show QuickShop about message
    default: true
  quickshop.info:
    description: Show QuickShop Statistics.
    default: op
  quickshop.fetchmessage:
    description: Use command /qs fetchmessage to manual fetch shop message from database. Will not effect auto fetch if you have it on...
    default: true
  quickshop.paste:
    description: Command to upload server information to Pastebin. !WARNING, This will upload your data and it may leak your server configuration and other sensitive information.
    default: op
  quickshop.preview:
    description: Permission for preview item to use a GUI
    default: true
  quickshop.tax:
    description: Permission to bypass Tax
    default: op
  quickshop.tax.bypassunlimited:
    description: Permission to bypass Tax but only for unlimited shop
    default: op
  quickshop.cleanghost:
    description: Permission to use /qs cleanghost
    default: op
  quickshop.reset:
    description: Permission to use /qs reset
    default: op
  quickshop.bypasscreatefee:
    description: Permission to bypass creation fee
    default: op
  quickshop.recovery:
    description: Permission to use /qs recovery, WARNING DO NOT EXECUTE THIS COMMAND IF YOU DID NOT KNOW WHAT WILL HAPPEND
    default: op
  quickshop.removeall.other:
    description: Permission to use /qs removeall <player> to remove other player shops
    default: op
  quickshop.removeall.self:
    description: Permission to use /qs removeall to remove player himself shops
    default: op
  quickshop.removeworld:
    description: Permission to us /qs removeworld
    default: op
  quickshop.currency:
    description: Permission to us /qs currency
    default: op
  quickshop.other.currency:
    description: Permission to us /qs currency but use for others shop
    default: op
  quickshop.showdisabled:
    description: Permission to see commands in help list if commands are disabled
    default: op

